services:
  - type: web
    name: frexy-auto-like-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8307741402:AAFp_k2nOq_hKheUOONX6e0kCcmTL6AstxY
      - key: ADMIN_ID
        value: 6417430059
      - key: PORT
        value: 8080
    healthCheckPath: /
